#!/bin/csh

if ( ! $?DGB_CVS_DIR ) then
    echo "Please source $WORK/dvs/set_dvs_env.csh"
    exit 1
endif

if ( $#argv < 1 ) then
    echo "Usage: $0 [-r <revision>] <file> "
    exit 1
endif


if ( "$1" == "-r" ) then
    shift
    set rev="-r $1"
    shift
else
    set rev=""
endif

set diffinp=$1
set reposfile=./CVS/Repository
if ( ! -e $reposfile ) then
    set filedir=`echo $1 | sed 's/\/.*$//'`
    cd $filedir
    set diffinp=`echo $diffinp|sed "s/$filedir\///"`
endif

set repos=`cat $reposfile`
dvs co -p ${rev} $repos/$diffinp > /tmp/mdiff.$$

tkdiff /tmp/mdiff.$$ $diffinp
\rm /tmp/mdiff.$$
