#!/bin/csh

set predcmd="dvs editors"
set edcmd="dvs_ed"
set startdir=`pwd`

foreach fil ( $* )
	if ( ! -r $fil || -d $fil ) continue
	echo -n "$fil ... "

	if ( $fil:t != $fil ) then

		echo -n "cd $fil:h ... "
		cd $fil:h
		set fil=$fil:t

	endif

	if ( `$predcmd $fil` == "" ) then

		echo -n "checking out ... "
		$edcmd $fil
		echo "done."

	else

		echo "already checked out."

	endif

	cd $startdir

end
