#!/bin/csh -f

if ( $#argv != 1 ) then
    echo "Usage : $0 file_to_see_last_change_of"
    exit 1
endif

set fil=$1

set rel=`dvs status $1 | grep 'Working revision:' | awk '{ print $3 }'`
set majrelnr=`echo $rel | sed 's/\..*$//'`
set minrelnr=`echo $rel | sed 's/.\.//'`
@ minrelnr = $minrelnr - 1
set prevrel=$majrelnr.$minrelnr

dvs diff -r$prevrel $fil
