#!/bin/csh

if ( ! $?DGB_CVS_DIR ) then
    echo "Please source $WORK/dvs/set_dvs_env.csh"
    exit 1
endif

if ( $#argv < 1 ) then
    echo "Usage: $0 [-r <revision>] <file> "
    exit 1
endif


if ( "$1" == "-r" ) then
    shift
    set rev="-r $1"
    shift
else
    set rev=""
endif

set repos=`cat ./CVS/Repository`
dvs co -p $rev $repos/$1 > /tmp/mdiff.$$

tkdiff /tmp/mdiff.$$ $*
\rm /tmp/mdiff.$$
