#!/bin/csh -f
# SVN: $Id$

if ( ! -d CVS ) then
    svn lock $*
    exit $status
endif


set exit_status=0
onintr goto finish_off
set editfil=/tmp/dvs_ed.$$

if ( ! $?DGB_CVS_DIR ) then
    echo "Please source $WORK/dvs/set_dvs_env.csh"
    exit 1
endif

cvs editors $* > $editfil 

set edit_size = `ls -l $editfil | awk '{print $5}'`
if ( $edit_size != 0 ) then
    echo "file(s) already edited: "
    cat $editfil

    echo "Continue? (y/n, default=n)"
    set answer = $<

    if ( $answer != "y" ) then

	echo "exiting."
	set exit_status=1
	goto finish_off

    endif

endif


dvs edit $*

finish_off:
rm -f $editfil
exit $exit_status
