#!/bin/csh -f
# SVN: $Id$

if ( $#argv < 2 ) then
    echo "Usage: $0 file-extension sub-dir [subdir ...]"
    exit 1
endif

if ( ! -d CVS ) then
    echo "No Subversion support yet"
    exit 1
endif

set statcmd="dvs status"
set ext=$1
shift

foreach dir ( $* )
    if ( -d $dir && "$dir" != "CVS" ) then
	echo "$dir ..."
	cd $dir
	$statcmd *.$ext > /dev/null
	cd ..
    endif
end
