#_______________________Pmake__________________________________________________
#
#	CopyRight:	dGB Beheer B.V.
# 	Dec 2012	Aneesh
#	RCS :		$Id$
#_______________________________________________________________________________


SET( BREAKPADDIR "" CACHE PATH "BREAKPAD Location" )

MACRO(OD_SETUP_BREAKPAD)
	IF ( (NOT DEFINED BREAKPADDIR) OR BREAKPADDIR STREQUAL "" )
	    MESSAGE("BREAKPADDIR NOT SET")
	ENDIF()

	FIND_LIBRARY( BREAKPADLIB NAMES BreakPad PATHS ${BREAKPADDIR}/client/windows/Debug/lib REQUIRED )
	FIND_LIBRARY( BREAKPADCOMMONLIB NAMES BreakPadCommon PATHS ${BREAKPADDIR}/client/windows/Debug/lib REQUIRED )
	FIND_LIBRARY( BREAKPADCLIENTLIB NAMES BreakPadClient PATHS ${BREAKPADDIR}/client/windows/Debug/lib REQUIRED )

	IF(OD_USEBREAKPAD)
	    LIST(APPEND OD_MODULE_INCLUDESYSPATH ${BREAKPADDIR})
	    SET(OD_BREAKPADLIBS ${BREAKPADLIB} ${BREAKPADCOMMONLIB} ${BREAKPADCLIENTLIB} )
	    ADD_DEFINITIONS( -DHAS_BREAKPAD )
	ENDIF()

	LIST(APPEND OD_MODULE_EXTERNAL_LIBS ${OD_BREAKPADLIBS} )
ENDMACRO(OD_SETUP_BREAKPAD)
