#_______________________Pmake__________________________________________________
#
#	CopyRight:	dGB Beheer B.V.
# 	Jan 2012	K. Tingdahl
#	RCS :		$Id: ODQtUtils.cmake,v 1.18 2012-07-23 11:29:54 cvskris Exp $
#_______________________________________________________________________________

SET(QTDIR "" CACHE PATH "QT Location" )

MACRO(OD_SETUP_QT)
    IF ( (NOT DEFINED QTDIR) OR QTDIR STREQUAL "" )
	MESSAGE( FATAL_ERROR "QTDIR not set")
    ENDIF()

    SET( ENV{QTDIR} ${QTDIR} )
    SET ( QT_QMAKE_EXECUTABLE ${QTDIR}/bin/qmake${CMAKE_EXECUTABLE_SUFFIX} )


    FIND_PACKAGE(Qt4 REQUIRED QtGui QtCore QtSql QtNetwork )
     
    include(${QT_USE_FILE})

    IF(${OD_USEQT} MATCHES "Core" )
	LIST(APPEND OD_MODULE_INCLUDESYSPATH
            ${QT_QTNETWORK_INCLUDE_DIR}
            ${QT_QTCORE_INCLUDE_DIR} ${QTDIR}/include )
        SET(OD_QT_LIBS ${QT_QTCORE_LIBRARY_RELEASE}
                       ${QT_QTNETWORK_LIBRARY_RELEASE})
    ENDIF()

    IF(${OD_USEQT} MATCHES "Sql" )
	LIST(APPEND OD_MODULE_INCLUDESYSPATH
            ${QT_QTSQL_INCLUDE_DIR}
            ${QTDIR}/include )
        SET(OD_QT_LIBS ${QT_QTSQL_LIBRARY_RELEASE})
    ENDIF()

    IF(${OD_USEQT} MATCHES "Gui")
	LIST(APPEND OD_MODULE_INCLUDESYSPATH
            ${QT_QTCORE_INCLUDE_DIR}
            ${QT_QTGUI_INCLUDE_DIR} ${QTDIR}/include )
        SET(OD_QT_LIBS ${QT_QTGUI_LIBRARY_RELEASE})
    ENDIF()

    IF(${OD_USEQT} MATCHES "OpenGL")
	LIST(APPEND OD_MODULE_INCLUDESYSPATH
            ${QT_QTOPENGL_INCLUDE_DIR} ${QTDIR}/include )
        SET(OD_QT_LIBS ${QT_QTOPENGL_LIBRARY_RELEASE})
    ENDIF()

    IF( QT_MOC_HEADERS )
        FOREACH( HEADER ${QT_MOC_HEADERS} )
            LIST(APPEND QT_MOC_INPUT
                ${CMAKE_SOURCE_DIR}/include/${OD_MODULE_NAME}/${HEADER})
        ENDFOREACH()

        QT4_WRAP_CPP (QT_MOC_OUTFILES ${QT_MOC_INPUT})
    ENDIF( QT_MOC_HEADERS )

    LIST(APPEND OD_MODULE_EXTERNAL_LIBS ${OD_QT_LIBS} )
    IF ( OD_SUBSYSTEM MATCHES ${OD_CORE_SUBSYSTEM} )
	INSTALL ( FILES ${QT_QTGUI_LIBRARY_RELEASE} ${QT_QTCORE_LIBRARY_RELEASE}
			${QT_QTSQL_LIBRARY_RELEASE} ${QT_QTNETWORK_LIBRARY_RELEASE}
		    DESTINATION ${OD_EXEC_INSTALL_PATH} )
    ENDIF()
ENDMACRO(OD_SETUP_QT)
