#!/bin/sh -f
# CopyRight:    Copyright(C): dGB Beheer B. V. 2013
# Description:  Script to launch installer
# Author:       Nageswara
# Date:         May 2013
# RCS:          $Id$

PLFNAME=`uname`
if [ "${PLFNAME}" = "Darwin" ]; then
    echo "Unsupported platform"
    exit 1
fi

if [ ! -f /bin/csh ]; then
    echo "You do not have csh installed which is required by OpendTect"
    echo "Please install csh or contact your system administrator."
    exit 1
fi

curdir=`dirname "$0"`
qtfile=${curdir}/../plugins/platforms/libqxcb.so
if [ ! -f "$qtfile" ]; then
    echo "Qt platform plugin file $qtfile not found."
    echo "Can not display the installer window without this file."
    exit 1
fi

infomsg=`ldd $qtfile | grep "not found"`
if [ "$infomsg" != "" ]; then
    echo  "System libraries listed below are missing, please install them and rerun the installer"
    echo "$infomsg"
    exit 1
fi

#get rid of the OD environment.
if [ $?DTECT_APPL ]; then
    export DTECT_APPL=""
fi

"${curdir}/od_instmgr" "$@"
exit $?
