#!/bin/bash
# CopyRight:    Copyright(C): dGB Beheer B. V. 2013
# Description:  Script to launch installer
# Author:       Nageswara
# Date:         May 2013

PLFNAME=`uname`
if [[ "${PLFNAME}" = "Darwin" ]]; then
    echo "Unsupported platform"
    exit 1
else
    if [[ -n "${DTECT_APPL}" ]]; then
	if [[ "${DTECT_APPL}" == *6.4.0 || "${DTECT_APPL}" == *6.2.0 ]]; then
	    unset LD_LIBRARY_PATH
	    export OD_UPDATE_FROM_LEGACY="yes"
	fi
    fi
fi

if [[ ! -f /bin/csh ]]; then
    echo "You do not have csh installed which is required by OpendTect"
    echo "Please install csh or contact your system administrator."
    exit 1
fi

scriptdir=`realpath $0`
curdir=`dirname $scriptdir`
qtfile=${curdir}/../plugins/platforms/libqxcb.so
if [[ ! -f "$qtfile" ]]; then
    echo "Qt platform plugin file $qtfile not found."
    echo "Can not display the installer window without this file."
    exit 1
fi

#check lib->Release link
if [[ ! -L ${curdir}/../lib ]]; then
    echo "${curdir}/../lib does not exist"
    echo "Please check your installation."
    echo "The installer can however continue normally."

    if [[ -n ${LD_LIBRARY_PATH} ]]; then
	export LD_LIBRARY_PATH=${curdir}:${LD_LIBRARY_PATH}
    else
	export LD_LIBRARY_PATH=${curdir}
    fi
fi

#check the presence of libpng in curdir
pngfilenm=`ls ${curdir} | grep "libpng*"`
if [[ -z $pngfilenm ]]; then
    echo -e "\npng library is missing"
    echo  "Cannot launch the installer without it."
    exit 1
fi

infomsg=`ldd $qtfile | grep "not found"`
if [[ -n "$infomsg" ]]; then
    infomsg=`ldd $qtfile | grep "not found" | grep -v $pngfilenm`
    if [[ -n "$infomsg" ]]; then
	echo  "System libraries listed below are missing, please install them and rerun the installer"
	echo "$infomsg"
        exit 1
    fi
fi

#get rid of the OD environment.
if [[ -n $DTECT_APPL ]]; then
    export DTECT_APPL=""
fi

if [[ -z "${OD_UPDATE_FROM_LEGACY}" ]]; then
    "${curdir}/od_instmgr" "$@"
    exit $?
fi

unset OD_UPDATE_FROM_LEGACY
outputstr=`"${curdir}/od_instmgr" "$@"`

if [[ ("$?" != 0) ]]; then
   exit $?
elif [[ "${outputstr}"=="Updates available" ]]; then
   exit 1
fi
