/*+
________________________________________________________________________

 Copyright:	(C) 1995-2022 dGB Beheer B.V.
 License:	https://dgbes.com/licensing
________________________________________________________________________

-*/

//This file is generated by marchingcubelistgen, and should not be edited manually.
    //Case 1
    triangles_[1].nrindices_ += 3;
    static char dummy0[] = { 0,0, 0,2, 0,1 };
    triangles_[1].indices_ += dummy0;

    //Case 1
    triangles_[4].nrindices_ += 3;
    static char dummy1[] = { 0,1, 2,2, 2,0 };
    triangles_[4].indices_ += dummy1;

    //Case 1
    triangles_[64].nrindices_ += 3;
    static char dummy2[] = { 2,0, 6,2, 4,1 };
    triangles_[64].indices_ += dummy2;

    //Case 1
    triangles_[16].nrindices_ += 3;
    static char dummy3[] = { 4,1, 4,2, 0,0 };
    triangles_[16].indices_ += dummy3;

    //Case 1
    triangles_[2].nrindices_ += 3;
    static char dummy4[] = { 0,2, 1,0, 1,1 };
    triangles_[2].indices_ += dummy4;

    //Case 1
    triangles_[8].nrindices_ += 3;
    static char dummy5[] = { 2,2, 1,1, 3,0 };
    triangles_[8].indices_ += dummy5;

    //Case 1
    triangles_[128].nrindices_ += 3;
    static char dummy6[] = { 6,2, 3,0, 5,1 };
    triangles_[128].indices_ += dummy6;

    //Case 1
    triangles_[32].nrindices_ += 3;
    static char dummy7[] = { 4,2, 5,1, 1,0 };
    triangles_[32].indices_ += dummy7;

    //Case 1
    triangles_[254].nrindices_ += 3;
    static char dummy8[] = { 0,1, 0,2, 0,0 };
    triangles_[254].indices_ += dummy8;

    //Case 1
    triangles_[251].nrindices_ += 3;
    static char dummy9[] = { 2,0, 2,2, 0,1 };
    triangles_[251].indices_ += dummy9;

    //Case 1
    triangles_[191].nrindices_ += 3;
    static char dummy10[] = { 4,1, 6,2, 2,0 };
    triangles_[191].indices_ += dummy10;

    //Case 1
    triangles_[239].nrindices_ += 3;
    static char dummy11[] = { 0,0, 4,2, 4,1 };
    triangles_[239].indices_ += dummy11;

    //Case 1
    triangles_[253].nrindices_ += 3;
    static char dummy12[] = { 1,1, 1,0, 0,2 };
    triangles_[253].indices_ += dummy12;

    //Case 1
    triangles_[247].nrindices_ += 3;
    static char dummy13[] = { 3,0, 1,1, 2,2 };
    triangles_[247].indices_ += dummy13;

    //Case 1
    triangles_[127].nrindices_ += 3;
    static char dummy14[] = { 5,1, 3,0, 6,2 };
    triangles_[127].indices_ += dummy14;

    //Case 1
    triangles_[223].nrindices_ += 3;
    static char dummy15[] = { 1,0, 5,1, 4,2 };
    triangles_[223].indices_ += dummy15;

    //Case 2
    triangles_[17].nrindices_ += 4;
    static char dummy16[] = { 0,2, 0,1, 4,2, 4,1 };
    triangles_[17].indices_ += dummy16;

    //Case 2
    triangles_[5].nrindices_ += 4;
    static char dummy17[] = { 2,2, 2,0, 0,2, 0,0 };
    triangles_[5].indices_ += dummy17;

    //Case 2
    triangles_[68].nrindices_ += 4;
    static char dummy18[] = { 6,2, 4,1, 2,2, 0,1 };
    triangles_[68].indices_ += dummy18;

    //Case 2
    triangles_[80].nrindices_ += 4;
    static char dummy19[] = { 4,2, 0,0, 6,2, 2,0 };
    triangles_[80].indices_ += dummy19;

    //Case 2
    triangles_[3].nrindices_ += 4;
    static char dummy20[] = { 1,0, 1,1, 0,0, 0,1 };
    triangles_[3].indices_ += dummy20;

    //Case 2
    triangles_[12].nrindices_ += 4;
    static char dummy21[] = { 1,1, 3,0, 0,1, 2,0 };
    triangles_[12].indices_ += dummy21;

    //Case 2
    triangles_[192].nrindices_ += 4;
    static char dummy22[] = { 3,0, 5,1, 2,0, 4,1 };
    triangles_[192].indices_ += dummy22;

    //Case 2
    triangles_[48].nrindices_ += 4;
    static char dummy23[] = { 5,1, 1,0, 4,1, 0,0 };
    triangles_[48].indices_ += dummy23;

    //Case 2
    triangles_[34].nrindices_ += 4;
    static char dummy24[] = { 4,2, 5,1, 0,2, 1,1 };
    triangles_[34].indices_ += dummy24;

    //Case 2
    triangles_[10].nrindices_ += 4;
    static char dummy25[] = { 0,2, 1,0, 2,2, 3,0 };
    triangles_[10].indices_ += dummy25;

    //Case 2
    triangles_[136].nrindices_ += 4;
    static char dummy26[] = { 2,2, 1,1, 6,2, 5,1 };
    triangles_[136].indices_ += dummy26;

    //Case 2
    triangles_[160].nrindices_ += 4;
    static char dummy27[] = { 6,2, 3,0, 4,2, 1,0 };
    triangles_[160].indices_ += dummy27;

    //Case 2
    triangles_[238].nrindices_ += 4;
    static char dummy28[] = { 0,1, 0,2, 4,1, 4,2 };
    triangles_[238].indices_ += dummy28;

    //Case 2
    triangles_[250].nrindices_ += 4;
    static char dummy29[] = { 2,0, 2,2, 0,0, 0,2 };
    triangles_[250].indices_ += dummy29;

    //Case 2
    triangles_[187].nrindices_ += 4;
    static char dummy30[] = { 4,1, 6,2, 0,1, 2,2 };
    triangles_[187].indices_ += dummy30;

    //Case 2
    triangles_[175].nrindices_ += 4;
    static char dummy31[] = { 0,0, 4,2, 2,0, 6,2 };
    triangles_[175].indices_ += dummy31;

    //Case 2
    triangles_[252].nrindices_ += 4;
    static char dummy32[] = { 1,1, 1,0, 0,1, 0,0 };
    triangles_[252].indices_ += dummy32;

    //Case 2
    triangles_[243].nrindices_ += 4;
    static char dummy33[] = { 3,0, 1,1, 2,0, 0,1 };
    triangles_[243].indices_ += dummy33;

    //Case 2
    triangles_[63].nrindices_ += 4;
    static char dummy34[] = { 5,1, 3,0, 4,1, 2,0 };
    triangles_[63].indices_ += dummy34;

    //Case 2
    triangles_[207].nrindices_ += 4;
    static char dummy35[] = { 1,0, 5,1, 0,0, 4,1 };
    triangles_[207].indices_ += dummy35;

    //Case 2
    triangles_[221].nrindices_ += 4;
    static char dummy36[] = { 5,1, 4,2, 1,1, 0,2 };
    triangles_[221].indices_ += dummy36;

    //Case 2
    triangles_[245].nrindices_ += 4;
    static char dummy37[] = { 1,0, 0,2, 3,0, 2,2 };
    triangles_[245].indices_ += dummy37;

    //Case 2
    triangles_[119].nrindices_ += 4;
    static char dummy38[] = { 1,1, 2,2, 5,1, 6,2 };
    triangles_[119].indices_ += dummy38;

    //Case 2
    triangles_[95].nrindices_ += 4;
    static char dummy39[] = { 3,0, 6,2, 1,0, 4,2 };
    triangles_[95].indices_ += dummy39;

    //Case 3
    triangles_[33].nrindices_ += 7;
    static char dummy40[] = { 0,0, 0,2, 0,1, -1, 1,0, 4,2, 5,1 };
    triangles_[33].indices_ += dummy40;

    //Case 3
    triangles_[6].nrindices_ += 7;
    static char dummy41[] = { 0,1, 2,2, 2,0, -1, 1,1, 0,2, 1,0 };
    triangles_[6].indices_ += dummy41;

    //Case 3
    triangles_[72].nrindices_ += 7;
    static char dummy42[] = { 2,0, 6,2, 4,1, -1, 3,0, 2,2, 1,1 };
    triangles_[72].indices_ += dummy42;

    //Case 3
    triangles_[144].nrindices_ += 7;
    static char dummy43[] = { 4,1, 4,2, 0,0, -1, 5,1, 6,2, 3,0 };
    triangles_[144].indices_ += dummy43;

    //Case 3
    triangles_[18].nrindices_ += 7;
    static char dummy44[] = { 0,2, 1,0, 1,1, -1, 4,2, 0,0, 4,1 };
    triangles_[18].indices_ += dummy44;

    //Case 3
    triangles_[9].nrindices_ += 7;
    static char dummy45[] = { 2,2, 1,1, 3,0, -1, 0,2, 0,1, 0,0 };
    triangles_[9].indices_ += dummy45;

    //Case 3
    triangles_[132].nrindices_ += 7;
    static char dummy46[] = { 6,2, 3,0, 5,1, -1, 2,2, 2,0, 0,1 };
    triangles_[132].indices_ += dummy46;

    //Case 3
    triangles_[96].nrindices_ += 7;
    static char dummy47[] = { 4,2, 5,1, 1,0, -1, 6,2, 4,1, 2,0 };
    triangles_[96].indices_ += dummy47;

    //Case 3
    triangles_[130].nrindices_ += 7;
    static char dummy48[] = { 1,0, 1,1, 0,2, -1, 3,0, 5,1, 6,2 };
    triangles_[130].indices_ += dummy48;

    //Case 3
    triangles_[40].nrindices_ += 7;
    static char dummy49[] = { 1,1, 3,0, 2,2, -1, 5,1, 1,0, 4,2 };
    triangles_[40].indices_ += dummy49;

    //Case 3
    triangles_[20].nrindices_ += 7;
    static char dummy50[] = { 0,0, 4,1, 4,2, -1, 2,0, 0,1, 2,2 };
    triangles_[20].indices_ += dummy50;

    //Case 3
    triangles_[65].nrindices_ += 7;
    static char dummy51[] = { 0,1, 0,0, 0,2, -1, 4,1, 2,0, 6,2 };
    triangles_[65].indices_ += dummy51;

    //Case 3
    triangles_[222].nrindices_ += 7;
    static char dummy52[] = { 0,1, 0,2, 0,0, -1, 5,1, 4,2, 1,0 };
    triangles_[222].indices_ += dummy52;

    //Case 3
    triangles_[249].nrindices_ += 7;
    static char dummy53[] = { 2,0, 2,2, 0,1, -1, 1,0, 0,2, 1,1 };
    triangles_[249].indices_ += dummy53;

    //Case 3
    triangles_[183].nrindices_ += 7;
    static char dummy54[] = { 4,1, 6,2, 2,0, -1, 1,1, 2,2, 3,0 };
    triangles_[183].indices_ += dummy54;

    //Case 3
    triangles_[111].nrindices_ += 7;
    static char dummy55[] = { 0,0, 4,2, 4,1, -1, 3,0, 6,2, 5,1 };
    triangles_[111].indices_ += dummy55;

    //Case 3
    triangles_[237].nrindices_ += 7;
    static char dummy56[] = { 1,1, 1,0, 0,2, -1, 4,1, 0,0, 4,2 };
    triangles_[237].indices_ += dummy56;

    //Case 3
    triangles_[246].nrindices_ += 7;
    static char dummy57[] = { 3,0, 1,1, 2,2, -1, 0,0, 0,1, 0,2 };
    triangles_[246].indices_ += dummy57;

    //Case 3
    triangles_[123].nrindices_ += 7;
    static char dummy58[] = { 5,1, 3,0, 6,2, -1, 0,1, 2,0, 2,2 };
    triangles_[123].indices_ += dummy58;

    //Case 3
    triangles_[159].nrindices_ += 7;
    static char dummy59[] = { 1,0, 5,1, 4,2, -1, 2,0, 4,1, 6,2 };
    triangles_[159].indices_ += dummy59;

    //Case 3
    triangles_[125].nrindices_ += 7;
    static char dummy60[] = { 0,2, 1,1, 1,0, -1, 6,2, 5,1, 3,0 };
    triangles_[125].indices_ += dummy60;

    //Case 3
    triangles_[215].nrindices_ += 7;
    static char dummy61[] = { 2,2, 3,0, 1,1, -1, 4,2, 1,0, 5,1 };
    triangles_[215].indices_ += dummy61;

    //Case 3
    triangles_[235].nrindices_ += 7;
    static char dummy62[] = { 4,2, 4,1, 0,0, -1, 2,2, 0,1, 2,0 };
    triangles_[235].indices_ += dummy62;

    //Case 3
    triangles_[190].nrindices_ += 7;
    static char dummy63[] = { 0,2, 0,0, 0,1, -1, 6,2, 2,0, 4,1 };
    triangles_[190].indices_ += dummy63;

    //Case 4
    triangles_[129].nrindices_ += 7;
    static char dummy64[] = { 0,0, 0,2, 0,1, -1, 5,1, 6,2, 3,0 };
    triangles_[129].indices_ += dummy64;

    //Case 4
    triangles_[36].nrindices_ += 7;
    static char dummy65[] = { 0,1, 2,2, 2,0, -1, 1,0, 4,2, 5,1 };
    triangles_[36].indices_ += dummy65;

    //Case 4
    triangles_[66].nrindices_ += 7;
    static char dummy66[] = { 2,0, 6,2, 4,1, -1, 1,1, 0,2, 1,0 };
    triangles_[66].indices_ += dummy66;

    //Case 4
    triangles_[24].nrindices_ += 7;
    static char dummy67[] = { 4,1, 4,2, 0,0, -1, 3,0, 2,2, 1,1 };
    triangles_[24].indices_ += dummy67;

    //Case 4
    triangles_[126].nrindices_ += 7;
    static char dummy68[] = { 0,1, 0,2, 0,0, -1, 3,0, 6,2, 5,1 };
    triangles_[126].indices_ += dummy68;

    //Case 4
    triangles_[219].nrindices_ += 7;
    static char dummy69[] = { 2,0, 2,2, 0,1, -1, 5,1, 4,2, 1,0 };
    triangles_[219].indices_ += dummy69;

    //Case 4
    triangles_[189].nrindices_ += 7;
    static char dummy70[] = { 4,1, 6,2, 2,0, -1, 1,0, 0,2, 1,1 };
    triangles_[189].indices_ += dummy70;

    //Case 4
    triangles_[231].nrindices_ += 7;
    static char dummy71[] = { 0,0, 4,2, 4,1, -1, 1,1, 2,2, 3,0 };
    triangles_[231].indices_ += dummy71;

    //Case 5
    triangles_[84].nrindices_ += 5;
    static char dummy72[] = { 0,0, 0,1, 4,2, 2,2, 6,2 };
    triangles_[84].indices_ += dummy72;

    //Case 5
    triangles_[81].nrindices_ += 5;
    static char dummy73[] = { 0,1, 2,0, 0,2, 6,2, 4,2 };
    triangles_[81].indices_ += dummy73;

    //Case 5
    triangles_[21].nrindices_ += 5;
    static char dummy74[] = { 2,0, 4,1, 2,2, 4,2, 0,2 };
    triangles_[21].indices_ += dummy74;

    //Case 5
    triangles_[69].nrindices_ += 5;
    static char dummy75[] = { 4,1, 0,0, 6,2, 0,2, 2,2 };
    triangles_[69].indices_ += dummy75;

    //Case 5
    triangles_[13].nrindices_ += 5;
    static char dummy76[] = { 0,2, 1,1, 0,0, 3,0, 2,0 };
    triangles_[13].indices_ += dummy76;

    //Case 5
    triangles_[196].nrindices_ += 5;
    static char dummy77[] = { 2,2, 3,0, 0,1, 5,1, 4,1 };
    triangles_[196].indices_ += dummy77;

    //Case 5
    triangles_[112].nrindices_ += 5;
    static char dummy78[] = { 6,2, 5,1, 2,0, 1,0, 0,0 };
    triangles_[112].indices_ += dummy78;

    //Case 5
    triangles_[19].nrindices_ += 5;
    static char dummy79[] = { 4,2, 1,0, 4,1, 1,1, 0,1 };
    triangles_[19].indices_ += dummy79;

    //Case 5
    triangles_[138].nrindices_ += 5;
    static char dummy80[] = { 1,0, 5,1, 0,2, 6,2, 2,2 };
    triangles_[138].indices_ += dummy80;

    //Case 5
    triangles_[168].nrindices_ += 5;
    static char dummy81[] = { 1,1, 1,0, 2,2, 4,2, 6,2 };
    triangles_[168].indices_ += dummy81;

    //Case 5
    triangles_[162].nrindices_ += 5;
    static char dummy82[] = { 3,0, 1,1, 6,2, 0,2, 4,2 };
    triangles_[162].indices_ += dummy82;

    //Case 5
    triangles_[42].nrindices_ += 5;
    static char dummy83[] = { 5,1, 3,0, 4,2, 2,2, 0,2 };
    triangles_[42].indices_ += dummy83;

    //Case 5
    triangles_[224].nrindices_ += 5;
    static char dummy84[] = { 4,2, 4,1, 1,0, 2,0, 3,0 };
    triangles_[224].indices_ += dummy84;

    //Case 5
    triangles_[50].nrindices_ += 5;
    static char dummy85[] = { 0,2, 0,0, 1,1, 4,1, 5,1 };
    triangles_[50].indices_ += dummy85;

    //Case 5
    triangles_[11].nrindices_ += 5;
    static char dummy86[] = { 2,2, 0,1, 3,0, 0,0, 1,0 };
    triangles_[11].indices_ += dummy86;

    //Case 5
    triangles_[140].nrindices_ += 5;
    static char dummy87[] = { 6,2, 2,0, 5,1, 0,1, 1,1 };
    triangles_[140].indices_ += dummy87;

    //Case 5
    triangles_[49].nrindices_ += 5;
    static char dummy88[] = { 1,0, 0,2, 5,1, 0,1, 4,1 };
    triangles_[49].indices_ += dummy88;

    //Case 5
    triangles_[7].nrindices_ += 5;
    static char dummy89[] = { 1,1, 2,2, 1,0, 2,0, 0,0 };
    triangles_[7].indices_ += dummy89;

    //Case 5
    triangles_[76].nrindices_ += 5;
    static char dummy90[] = { 3,0, 6,2, 1,1, 4,1, 0,1 };
    triangles_[76].indices_ += dummy90;

    //Case 5
    triangles_[208].nrindices_ += 5;
    static char dummy91[] = { 5,1, 4,2, 3,0, 0,0, 2,0 };
    triangles_[208].indices_ += dummy91;

    //Case 5
    triangles_[35].nrindices_ += 5;
    static char dummy92[] = { 0,0, 4,2, 0,1, 5,1, 1,1 };
    triangles_[35].indices_ += dummy92;

    //Case 5
    triangles_[14].nrindices_ += 5;
    static char dummy93[] = { 0,1, 0,2, 2,0, 1,0, 3,0 };
    triangles_[14].indices_ += dummy93;

    //Case 5
    triangles_[200].nrindices_ += 5;
    static char dummy94[] = { 2,0, 2,2, 4,1, 1,1, 5,1 };
    triangles_[200].indices_ += dummy94;

    //Case 5
    triangles_[176].nrindices_ += 5;
    static char dummy95[] = { 4,1, 6,2, 0,0, 3,0, 1,0 };
    triangles_[176].indices_ += dummy95;

    //Case 5
    triangles_[171].nrindices_ += 5;
    static char dummy96[] = { 6,2, 2,2, 4,2, 0,1, 0,0 };
    triangles_[171].indices_ += dummy96;

    //Case 5
    triangles_[174].nrindices_ += 5;
    static char dummy97[] = { 4,2, 6,2, 0,2, 2,0, 0,1 };
    triangles_[174].indices_ += dummy97;

    //Case 5
    triangles_[234].nrindices_ += 5;
    static char dummy98[] = { 0,2, 4,2, 2,2, 4,1, 2,0 };
    triangles_[234].indices_ += dummy98;

    //Case 5
    triangles_[186].nrindices_ += 5;
    static char dummy99[] = { 2,2, 0,2, 6,2, 0,0, 4,1 };
    triangles_[186].indices_ += dummy99;

    //Case 5
    triangles_[242].nrindices_ += 5;
    static char dummy100[] = { 2,0, 3,0, 0,0, 1,1, 0,2 };
    triangles_[242].indices_ += dummy100;

    //Case 5
    triangles_[59].nrindices_ += 5;
    static char dummy101[] = { 4,1, 5,1, 0,1, 3,0, 2,2 };
    triangles_[59].indices_ += dummy101;

    //Case 5
    triangles_[143].nrindices_ += 5;
    static char dummy102[] = { 0,0, 1,0, 2,0, 5,1, 6,2 };
    triangles_[143].indices_ += dummy102;

    //Case 5
    triangles_[236].nrindices_ += 5;
    static char dummy103[] = { 0,1, 1,1, 4,1, 1,0, 4,2 };
    triangles_[236].indices_ += dummy103;

    //Case 5
    triangles_[117].nrindices_ += 5;
    static char dummy104[] = { 2,2, 6,2, 0,2, 5,1, 1,0 };
    triangles_[117].indices_ += dummy104;

    //Case 5
    triangles_[87].nrindices_ += 5;
    static char dummy105[] = { 6,2, 4,2, 2,2, 1,0, 1,1 };
    triangles_[87].indices_ += dummy105;

    //Case 5
    triangles_[93].nrindices_ += 5;
    static char dummy106[] = { 4,2, 0,2, 6,2, 1,1, 3,0 };
    triangles_[93].indices_ += dummy106;

    //Case 5
    triangles_[213].nrindices_ += 5;
    static char dummy107[] = { 0,2, 2,2, 4,2, 3,0, 5,1 };
    triangles_[213].indices_ += dummy107;

    //Case 5
    triangles_[31].nrindices_ += 5;
    static char dummy108[] = { 3,0, 2,0, 1,0, 4,1, 4,2 };
    triangles_[31].indices_ += dummy108;

    //Case 5
    triangles_[205].nrindices_ += 5;
    static char dummy109[] = { 5,1, 4,1, 1,1, 0,0, 0,2 };
    triangles_[205].indices_ += dummy109;

    //Case 5
    triangles_[244].nrindices_ += 5;
    static char dummy110[] = { 1,0, 0,0, 3,0, 0,1, 2,2 };
    triangles_[244].indices_ += dummy110;

    //Case 5
    triangles_[115].nrindices_ += 5;
    static char dummy111[] = { 1,1, 0,1, 5,1, 2,0, 6,2 };
    triangles_[115].indices_ += dummy111;

    //Case 5
    triangles_[206].nrindices_ += 5;
    static char dummy112[] = { 4,1, 0,1, 5,1, 0,2, 1,0 };
    triangles_[206].indices_ += dummy112;

    //Case 5
    triangles_[248].nrindices_ += 5;
    static char dummy113[] = { 0,0, 2,0, 1,0, 2,2, 1,1 };
    triangles_[248].indices_ += dummy113;

    //Case 5
    triangles_[179].nrindices_ += 5;
    static char dummy114[] = { 0,1, 4,1, 1,1, 6,2, 3,0 };
    triangles_[179].indices_ += dummy114;

    //Case 5
    triangles_[47].nrindices_ += 5;
    static char dummy115[] = { 2,0, 0,0, 3,0, 4,2, 5,1 };
    triangles_[47].indices_ += dummy115;

    //Case 5
    triangles_[220].nrindices_ += 5;
    static char dummy116[] = { 1,1, 5,1, 0,1, 4,2, 0,0 };
    triangles_[220].indices_ += dummy116;

    //Case 5
    triangles_[241].nrindices_ += 5;
    static char dummy117[] = { 3,0, 1,0, 2,0, 0,2, 0,1 };
    triangles_[241].indices_ += dummy117;

    //Case 5
    triangles_[55].nrindices_ += 5;
    static char dummy118[] = { 5,1, 1,1, 4,1, 2,2, 2,0 };
    triangles_[55].indices_ += dummy118;

    //Case 5
    triangles_[79].nrindices_ += 5;
    static char dummy119[] = { 1,0, 3,0, 0,0, 6,2, 4,1 };
    triangles_[79].indices_ += dummy119;

    //Case 6
    triangles_[145].nrindices_ += 8;
    static char dummy120[] = { 0,2, 0,1, 4,2, 4,1, -1, 5,1, 6,2, 3,0 };
    triangles_[145].indices_ += dummy120;

    //Case 6
    triangles_[37].nrindices_ += 8;
    static char dummy121[] = { 2,2, 2,0, 0,2, 0,0, -1, 1,0, 4,2, 5,1 };
    triangles_[37].indices_ += dummy121;

    //Case 6
    triangles_[70].nrindices_ += 8;
    static char dummy122[] = { 6,2, 4,1, 2,2, 0,1, -1, 1,1, 0,2, 1,0 };
    triangles_[70].indices_ += dummy122;

    //Case 6
    triangles_[88].nrindices_ += 8;
    static char dummy123[] = { 4,2, 0,0, 6,2, 2,0, -1, 3,0, 2,2, 1,1 };
    triangles_[88].indices_ += dummy123;

    //Case 6
    triangles_[67].nrindices_ += 8;
    static char dummy124[] = { 1,0, 1,1, 0,0, 0,1, -1, 4,1, 2,0, 6,2 };
    triangles_[67].indices_ += dummy124;

    //Case 6
    triangles_[28].nrindices_ += 8;
    static char dummy125[] = { 1,1, 3,0, 0,1, 2,0, -1, 0,0, 4,1, 4,2 };
    triangles_[28].indices_ += dummy125;

    //Case 6
    triangles_[193].nrindices_ += 8;
    static char dummy126[] = { 3,0, 5,1, 2,0, 4,1, -1, 0,1, 0,0, 0,2 };
    triangles_[193].indices_ += dummy126;

    //Case 6
    triangles_[52].nrindices_ += 8;
    static char dummy127[] = { 5,1, 1,0, 4,1, 0,0, -1, 2,0, 0,1, 2,2 };
    triangles_[52].indices_ += dummy127;

    //Case 6
    triangles_[38].nrindices_ += 8;
    static char dummy128[] = { 4,2, 5,1, 0,2, 1,1, -1, 0,1, 2,2, 2,0 };
    triangles_[38].indices_ += dummy128;

    //Case 6
    triangles_[74].nrindices_ += 8;
    static char dummy129[] = { 0,2, 1,0, 2,2, 3,0, -1, 2,0, 6,2, 4,1 };
    triangles_[74].indices_ += dummy129;

    //Case 6
    triangles_[152].nrindices_ += 8;
    static char dummy130[] = { 2,2, 1,1, 6,2, 5,1, -1, 4,1, 4,2, 0,0 };
    triangles_[152].indices_ += dummy130;

    //Case 6
    triangles_[161].nrindices_ += 8;
    static char dummy131[] = { 6,2, 3,0, 4,2, 1,0, -1, 0,0, 0,2, 0,1 };
    triangles_[161].indices_ += dummy131;

    //Case 6
    triangles_[56].nrindices_ += 8;
    static char dummy132[] = { 0,0, 4,1, 1,0, 5,1, -1, 1,1, 3,0, 2,2 };
    triangles_[56].indices_ += dummy132;

    //Case 6
    triangles_[131].nrindices_ += 8;
    static char dummy133[] = { 0,1, 0,0, 1,1, 1,0, -1, 3,0, 5,1, 6,2 };
    triangles_[131].indices_ += dummy133;

    //Case 6
    triangles_[44].nrindices_ += 8;
    static char dummy134[] = { 2,0, 0,1, 3,0, 1,1, -1, 5,1, 1,0, 4,2 };
    triangles_[44].indices_ += dummy134;

    //Case 6
    triangles_[194].nrindices_ += 8;
    static char dummy135[] = { 4,1, 2,0, 5,1, 3,0, -1, 1,0, 1,1, 0,2 };
    triangles_[194].indices_ += dummy135;

    //Case 6
    triangles_[98].nrindices_ += 8;
    static char dummy136[] = { 1,1, 0,2, 5,1, 4,2, -1, 6,2, 4,1, 2,0 };
    triangles_[98].indices_ += dummy136;

    //Case 6
    triangles_[26].nrindices_ += 8;
    static char dummy137[] = { 3,0, 2,2, 1,0, 0,2, -1, 4,2, 0,0, 4,1 };
    triangles_[26].indices_ += dummy137;

    //Case 6
    triangles_[137].nrindices_ += 8;
    static char dummy138[] = { 5,1, 6,2, 1,1, 2,2, -1, 0,2, 0,1, 0,0 };
    triangles_[137].indices_ += dummy138;

    //Case 6
    triangles_[164].nrindices_ += 8;
    static char dummy139[] = { 1,0, 4,2, 3,0, 6,2, -1, 2,2, 2,0, 0,1 };
    triangles_[164].indices_ += dummy139;

    //Case 6
    triangles_[25].nrindices_ += 8;
    static char dummy140[] = { 4,1, 4,2, 0,1, 0,2, -1, 2,2, 1,1, 3,0 };
    triangles_[25].indices_ += dummy140;

    //Case 6
    triangles_[133].nrindices_ += 8;
    static char dummy141[] = { 0,0, 0,2, 2,0, 2,2, -1, 6,2, 3,0, 5,1 };
    triangles_[133].indices_ += dummy141;

    //Case 6
    triangles_[100].nrindices_ += 8;
    static char dummy142[] = { 0,1, 2,2, 4,1, 6,2, -1, 4,2, 5,1, 1,0 };
    triangles_[100].indices_ += dummy142;

    //Case 6
    triangles_[82].nrindices_ += 8;
    static char dummy143[] = { 2,0, 6,2, 0,0, 4,2, -1, 0,2, 1,0, 1,1 };
    triangles_[82].indices_ += dummy143;

    //Case 6
    triangles_[110].nrindices_ += 8;
    static char dummy144[] = { 0,1, 0,2, 4,1, 4,2, -1, 3,0, 6,2, 5,1 };
    triangles_[110].indices_ += dummy144;

    //Case 6
    triangles_[218].nrindices_ += 8;
    static char dummy145[] = { 2,0, 2,2, 0,0, 0,2, -1, 5,1, 4,2, 1,0 };
    triangles_[218].indices_ += dummy145;

    //Case 6
    triangles_[185].nrindices_ += 8;
    static char dummy146[] = { 4,1, 6,2, 0,1, 2,2, -1, 1,0, 0,2, 1,1 };
    triangles_[185].indices_ += dummy146;

    //Case 6
    triangles_[167].nrindices_ += 8;
    static char dummy147[] = { 0,0, 4,2, 2,0, 6,2, -1, 1,1, 2,2, 3,0 };
    triangles_[167].indices_ += dummy147;

    //Case 6
    triangles_[188].nrindices_ += 8;
    static char dummy148[] = { 1,1, 1,0, 0,1, 0,0, -1, 6,2, 2,0, 4,1 };
    triangles_[188].indices_ += dummy148;

    //Case 6
    triangles_[227].nrindices_ += 8;
    static char dummy149[] = { 3,0, 1,1, 2,0, 0,1, -1, 4,2, 4,1, 0,0 };
    triangles_[227].indices_ += dummy149;

    //Case 6
    triangles_[62].nrindices_ += 8;
    static char dummy150[] = { 5,1, 3,0, 4,1, 2,0, -1, 0,2, 0,0, 0,1 };
    triangles_[62].indices_ += dummy150;

    //Case 6
    triangles_[203].nrindices_ += 8;
    static char dummy151[] = { 1,0, 5,1, 0,0, 4,1, -1, 2,2, 0,1, 2,0 };
    triangles_[203].indices_ += dummy151;

    //Case 6
    triangles_[217].nrindices_ += 8;
    static char dummy152[] = { 5,1, 4,2, 1,1, 0,2, -1, 2,0, 2,2, 0,1 };
    triangles_[217].indices_ += dummy152;

    //Case 6
    triangles_[181].nrindices_ += 8;
    static char dummy153[] = { 1,0, 0,2, 3,0, 2,2, -1, 4,1, 6,2, 2,0 };
    triangles_[181].indices_ += dummy153;

    //Case 6
    triangles_[103].nrindices_ += 8;
    static char dummy154[] = { 1,1, 2,2, 5,1, 6,2, -1, 0,0, 4,2, 4,1 };
    triangles_[103].indices_ += dummy154;

    //Case 6
    triangles_[94].nrindices_ += 8;
    static char dummy155[] = { 3,0, 6,2, 1,0, 4,2, -1, 0,1, 0,2, 0,0 };
    triangles_[94].indices_ += dummy155;

    //Case 6
    triangles_[199].nrindices_ += 8;
    static char dummy156[] = { 4,1, 0,0, 5,1, 1,0, -1, 2,2, 3,0, 1,1 };
    triangles_[199].indices_ += dummy156;

    //Case 6
    triangles_[124].nrindices_ += 8;
    static char dummy157[] = { 0,0, 0,1, 1,0, 1,1, -1, 6,2, 5,1, 3,0 };
    triangles_[124].indices_ += dummy157;

    //Case 6
    triangles_[211].nrindices_ += 8;
    static char dummy158[] = { 0,1, 2,0, 1,1, 3,0, -1, 4,2, 1,0, 5,1 };
    triangles_[211].indices_ += dummy158;

    //Case 6
    triangles_[61].nrindices_ += 8;
    static char dummy159[] = { 2,0, 4,1, 3,0, 5,1, -1, 0,2, 1,1, 1,0 };
    triangles_[61].indices_ += dummy159;

    //Case 6
    triangles_[157].nrindices_ += 8;
    static char dummy160[] = { 0,2, 1,1, 4,2, 5,1, -1, 2,0, 4,1, 6,2 };
    triangles_[157].indices_ += dummy160;

    //Case 6
    triangles_[229].nrindices_ += 8;
    static char dummy161[] = { 2,2, 3,0, 0,2, 1,0, -1, 4,1, 0,0, 4,2 };
    triangles_[229].indices_ += dummy161;

    //Case 6
    triangles_[118].nrindices_ += 8;
    static char dummy162[] = { 6,2, 5,1, 2,2, 1,1, -1, 0,0, 0,1, 0,2 };
    triangles_[118].indices_ += dummy162;

    //Case 6
    triangles_[91].nrindices_ += 8;
    static char dummy163[] = { 4,2, 1,0, 6,2, 3,0, -1, 0,1, 2,0, 2,2 };
    triangles_[91].indices_ += dummy163;

    //Case 6
    triangles_[230].nrindices_ += 8;
    static char dummy164[] = { 4,2, 4,1, 0,2, 0,1, -1, 3,0, 1,1, 2,2 };
    triangles_[230].indices_ += dummy164;

    //Case 6
    triangles_[122].nrindices_ += 8;
    static char dummy165[] = { 0,2, 0,0, 2,2, 2,0, -1, 5,1, 3,0, 6,2 };
    triangles_[122].indices_ += dummy165;

    //Case 6
    triangles_[155].nrindices_ += 8;
    static char dummy166[] = { 2,2, 0,1, 6,2, 4,1, -1, 1,0, 5,1, 4,2 };
    triangles_[155].indices_ += dummy166;

    //Case 6
    triangles_[173].nrindices_ += 8;
    static char dummy167[] = { 6,2, 2,0, 4,2, 0,0, -1, 1,1, 1,0, 0,2 };
    triangles_[173].indices_ += dummy167;

    //Case 7
    triangles_[146].nrindices_ += 11;
    static char dummy168[] = { 1,0, 1,1, 0,2, -1, 5,1, 6,2, 3,0, -1, 0,0, 4,1, 4,2 };
    triangles_[146].indices_ += dummy168;

    //Case 7
    triangles_[41].nrindices_ += 11;
    static char dummy169[] = { 1,1, 3,0, 2,2, -1, 1,0, 4,2, 5,1, -1, 0,1, 0,0, 0,2 };
    triangles_[41].indices_ += dummy169;

    //Case 7
    triangles_[134].nrindices_ += 11;
    static char dummy170[] = { 3,0, 5,1, 6,2, -1, 1,1, 0,2, 1,0, -1, 2,0, 0,1, 2,2 };
    triangles_[134].indices_ += dummy170;

    //Case 7
    triangles_[104].nrindices_ += 11;
    static char dummy171[] = { 5,1, 1,0, 4,2, -1, 3,0, 2,2, 1,1, -1, 4,1, 2,0, 6,2 };
    triangles_[104].indices_ += dummy171;

    //Case 7
    triangles_[97].nrindices_ += 11;
    static char dummy172[] = { 4,2, 5,1, 1,0, -1, 4,1, 2,0, 6,2, -1, 0,2, 0,1, 0,0 };
    triangles_[97].indices_ += dummy172;

    //Case 7
    triangles_[22].nrindices_ += 11;
    static char dummy173[] = { 0,2, 1,0, 1,1, -1, 0,0, 4,1, 4,2, -1, 2,2, 2,0, 0,1 };
    triangles_[22].indices_ += dummy173;

    //Case 7
    triangles_[73].nrindices_ += 11;
    static char dummy174[] = { 2,2, 1,1, 3,0, -1, 0,1, 0,0, 0,2, -1, 6,2, 4,1, 2,0 };
    triangles_[73].indices_ += dummy174;

    //Case 7
    triangles_[148].nrindices_ += 11;
    static char dummy175[] = { 6,2, 3,0, 5,1, -1, 2,0, 0,1, 2,2, -1, 4,2, 0,0, 4,1 };
    triangles_[148].indices_ += dummy175;

    //Case 7
    triangles_[109].nrindices_ += 11;
    static char dummy176[] = { 0,2, 1,1, 1,0, -1, 0,2, 1,1, 1,0, -1, 4,2, 4,1, 0,0 };
    triangles_[109].indices_ += dummy176;

    //Case 7
    triangles_[214].nrindices_ += 11;
    static char dummy177[] = { 2,2, 3,0, 1,1, -1, 2,2, 3,0, 1,1, -1, 0,2, 0,0, 0,1 };
    triangles_[214].indices_ += dummy177;

    //Case 7
    triangles_[121].nrindices_ += 11;
    static char dummy178[] = { 6,2, 5,1, 3,0, -1, 6,2, 5,1, 3,0, -1, 2,2, 0,1, 2,0 };
    triangles_[121].indices_ += dummy178;

    //Case 7
    triangles_[151].nrindices_ += 11;
    static char dummy179[] = { 4,2, 1,0, 5,1, -1, 4,2, 1,0, 5,1, -1, 6,2, 2,0, 4,1 };
    triangles_[151].indices_ += dummy179;

    //Case 7
    triangles_[158].nrindices_ += 11;
    static char dummy180[] = { 1,0, 5,1, 4,2, -1, 1,0, 5,1, 4,2, -1, 0,0, 0,1, 0,2 };
    triangles_[158].indices_ += dummy180;

    //Case 7
    triangles_[233].nrindices_ += 11;
    static char dummy181[] = { 1,1, 1,0, 0,2, -1, 1,1, 1,0, 0,2, -1, 0,1, 2,0, 2,2 };
    triangles_[233].indices_ += dummy181;

    //Case 7
    triangles_[182].nrindices_ += 11;
    static char dummy182[] = { 3,0, 1,1, 2,2, -1, 3,0, 1,1, 2,2, -1, 2,0, 4,1, 6,2 };
    triangles_[182].indices_ += dummy182;

    //Case 7
    triangles_[107].nrindices_ += 11;
    static char dummy183[] = { 5,1, 3,0, 6,2, -1, 5,1, 3,0, 6,2, -1, 4,1, 0,0, 4,2 };
    triangles_[107].indices_ += dummy183;

    //Case 8
    triangles_[85].nrindices_ += 4;
    static char dummy184[] = { 4,2, 0,2, 6,2, 2,2 };
    triangles_[85].indices_ += dummy184;

    //Case 8
    triangles_[15].nrindices_ += 4;
    static char dummy185[] = { 0,0, 1,0, 2,0, 3,0 };
    triangles_[15].indices_ += dummy185;

    //Case 8
    triangles_[204].nrindices_ += 4;
    static char dummy186[] = { 0,1, 1,1, 4,1, 5,1 };
    triangles_[204].indices_ += dummy186;

    //Case 8
    triangles_[240].nrindices_ += 4;
    static char dummy187[] = { 2,0, 3,0, 0,0, 1,0 };
    triangles_[240].indices_ += dummy187;

    //Case 8
    triangles_[51].nrindices_ += 4;
    static char dummy188[] = { 4,1, 5,1, 0,1, 1,1 };
    triangles_[51].indices_ += dummy188;

    //Case 8
    triangles_[170].nrindices_ += 4;
    static char dummy189[] = { 0,2, 4,2, 2,2, 6,2 };
    triangles_[170].indices_ += dummy189;

    //Case 9
    triangles_[77].nrindices_ += 6;
    static char dummy190[] = { 0,0, 0,2, 4,1, 1,1, 6,2, 3,0 };
    triangles_[77].indices_ += dummy190;

    //Case 9
    triangles_[212].nrindices_ += 6;
    static char dummy191[] = { 0,1, 2,2, 0,0, 3,0, 4,2, 5,1 };
    triangles_[212].indices_ += dummy191;

    //Case 9
    triangles_[113].nrindices_ += 6;
    static char dummy192[] = { 2,0, 6,2, 0,1, 5,1, 0,2, 1,0 };
    triangles_[113].indices_ += dummy192;

    //Case 9
    triangles_[23].nrindices_ += 6;
    static char dummy193[] = { 4,1, 4,2, 2,0, 1,0, 2,2, 1,1 };
    triangles_[23].indices_ += dummy193;

    //Case 9
    triangles_[142].nrindices_ += 6;
    static char dummy194[] = { 0,2, 1,0, 0,1, 5,1, 2,0, 6,2 };
    triangles_[142].indices_ += dummy194;

    //Case 9
    triangles_[232].nrindices_ += 6;
    static char dummy195[] = { 2,2, 1,1, 2,0, 1,0, 4,1, 4,2 };
    triangles_[232].indices_ += dummy195;

    //Case 9
    triangles_[178].nrindices_ += 6;
    static char dummy196[] = { 6,2, 3,0, 4,1, 1,1, 0,0, 0,2 };
    triangles_[178].indices_ += dummy196;

    //Case 9
    triangles_[43].nrindices_ += 6;
    static char dummy197[] = { 4,2, 5,1, 0,0, 3,0, 0,1, 2,2 };
    triangles_[43].indices_ += dummy197;

    //Case 10
    triangles_[195].nrindices_ += 9;
    static char dummy198[] = { 0,0, 1,0, 0,1, 1,1, -1, 4,1, 2,0, 5,1, 3,0 };
    triangles_[195].indices_ += dummy198;

    //Case 10
    triangles_[60].nrindices_ += 9;
    static char dummy199[] = { 0,1, 1,1, 2,0, 3,0, -1, 0,0, 4,1, 1,0, 5,1 };
    triangles_[60].indices_ += dummy199;

    //Case 10
    triangles_[102].nrindices_ += 9;
    static char dummy200[] = { 0,2, 4,2, 1,1, 5,1, -1, 0,1, 2,2, 4,1, 6,2 };
    triangles_[102].indices_ += dummy200;

    //Case 10
    triangles_[90].nrindices_ += 9;
    static char dummy201[] = { 2,2, 0,2, 3,0, 1,0, -1, 2,0, 6,2, 0,0, 4,2 };
    triangles_[90].indices_ += dummy201;

    //Case 10
    triangles_[153].nrindices_ += 9;
    static char dummy202[] = { 6,2, 2,2, 5,1, 1,1, -1, 4,1, 4,2, 0,1, 0,2 };
    triangles_[153].indices_ += dummy202;

    //Case 10
    triangles_[165].nrindices_ += 9;
    static char dummy203[] = { 4,2, 6,2, 1,0, 3,0, -1, 0,0, 0,2, 2,0, 2,2 };
    triangles_[165].indices_ += dummy203;

    //Case 11
    triangles_[197].nrindices_ += 9;
    static char dummy204[] = { 4,1, 0,0, 5,1, 2,2, 3,0, -1, 0,0, 0,2, 2,2 };
    triangles_[197].indices_ += dummy204;

    //Case 11
    triangles_[116].nrindices_ += 9;
    static char dummy205[] = { 0,0, 0,1, 1,0, 6,2, 5,1, -1, 0,1, 2,2, 6,2 };
    triangles_[116].indices_ += dummy205;

    //Case 11
    triangles_[83].nrindices_ += 9;
    static char dummy206[] = { 0,1, 2,0, 1,1, 4,2, 1,0, -1, 2,0, 6,2, 4,2 };
    triangles_[83].indices_ += dummy206;

    //Case 11
    triangles_[29].nrindices_ += 9;
    static char dummy207[] = { 2,0, 4,1, 3,0, 0,2, 1,1, -1, 4,1, 4,2, 0,2 };
    triangles_[29].indices_ += dummy207;

    //Case 11
    triangles_[78].nrindices_ += 9;
    static char dummy208[] = { 0,1, 0,2, 4,1, 3,0, 6,2, -1, 0,2, 1,0, 3,0 };
    triangles_[78].indices_ += dummy208;

    //Case 11
    triangles_[216].nrindices_ += 9;
    static char dummy209[] = { 2,0, 2,2, 0,0, 5,1, 4,2, -1, 2,2, 1,1, 5,1 };
    triangles_[216].indices_ += dummy209;

    //Case 11
    triangles_[177].nrindices_ += 9;
    static char dummy210[] = { 4,1, 6,2, 0,1, 1,0, 0,2, -1, 6,2, 3,0, 1,0 };
    triangles_[177].indices_ += dummy210;

    //Case 11
    triangles_[39].nrindices_ += 9;
    static char dummy211[] = { 0,0, 4,2, 2,0, 1,1, 2,2, -1, 4,2, 5,1, 1,1 };
    triangles_[39].indices_ += dummy211;

    //Case 11
    triangles_[172].nrindices_ += 9;
    static char dummy212[] = { 1,1, 1,0, 0,1, 6,2, 2,0, -1, 1,0, 4,2, 6,2 };
    triangles_[172].indices_ += dummy212;

    //Case 11
    triangles_[226].nrindices_ += 9;
    static char dummy213[] = { 3,0, 1,1, 2,0, 4,2, 4,1, -1, 1,1, 0,2, 4,2 };
    triangles_[226].indices_ += dummy213;

    //Case 11
    triangles_[58].nrindices_ += 9;
    static char dummy214[] = { 5,1, 3,0, 4,1, 0,2, 0,0, -1, 3,0, 2,2, 0,2 };
    triangles_[58].indices_ += dummy214;

    //Case 11
    triangles_[139].nrindices_ += 9;
    static char dummy215[] = { 1,0, 5,1, 0,0, 2,2, 0,1, -1, 5,1, 6,2, 2,2 };
    triangles_[139].indices_ += dummy215;

    //Case 12
    triangles_[86].nrindices_ += 9;
    static char dummy216[] = { 1,0, 1,1, 0,2, -1, 0,0, 0,1, 4,2, 2,2, 6,2 };
    triangles_[86].indices_ += dummy216;

    //Case 12
    triangles_[89].nrindices_ += 9;
    static char dummy217[] = { 1,1, 3,0, 2,2, -1, 0,1, 2,0, 0,2, 6,2, 4,2 };
    triangles_[89].indices_ += dummy217;

    //Case 12
    triangles_[149].nrindices_ += 9;
    static char dummy218[] = { 3,0, 5,1, 6,2, -1, 2,0, 4,1, 2,2, 4,2, 0,2 };
    triangles_[149].indices_ += dummy218;

    //Case 12
    triangles_[101].nrindices_ += 9;
    static char dummy219[] = { 5,1, 1,0, 4,2, -1, 4,1, 0,0, 6,2, 0,2, 2,2 };
    triangles_[101].indices_ += dummy219;

    //Case 12
    triangles_[45].nrindices_ += 9;
    static char dummy220[] = { 4,2, 5,1, 1,0, -1, 0,2, 1,1, 0,0, 3,0, 2,0 };
    triangles_[45].indices_ += dummy220;

    //Case 12
    triangles_[198].nrindices_ += 9;
    static char dummy221[] = { 0,2, 1,0, 1,1, -1, 2,2, 3,0, 0,1, 5,1, 4,1 };
    triangles_[198].indices_ += dummy221;

    //Case 12
    triangles_[120].nrindices_ += 9;
    static char dummy222[] = { 2,2, 1,1, 3,0, -1, 6,2, 5,1, 2,0, 1,0, 0,0 };
    triangles_[120].indices_ += dummy222;

    //Case 12
    triangles_[147].nrindices_ += 9;
    static char dummy223[] = { 6,2, 3,0, 5,1, -1, 4,2, 1,0, 4,1, 1,1, 0,1 };
    triangles_[147].indices_ += dummy223;

    //Case 12
    triangles_[154].nrindices_ += 9;
    static char dummy224[] = { 0,0, 4,1, 4,2, -1, 1,0, 5,1, 0,2, 6,2, 2,2 };
    triangles_[154].indices_ += dummy224;

    //Case 12
    triangles_[169].nrindices_ += 9;
    static char dummy225[] = { 0,1, 0,0, 0,2, -1, 1,1, 1,0, 2,2, 4,2, 6,2 };
    triangles_[169].indices_ += dummy225;

    //Case 12
    triangles_[166].nrindices_ += 9;
    static char dummy226[] = { 2,0, 0,1, 2,2, -1, 3,0, 1,1, 6,2, 0,2, 4,2 };
    triangles_[166].indices_ += dummy226;

    //Case 12
    triangles_[106].nrindices_ += 9;
    static char dummy227[] = { 4,1, 2,0, 6,2, -1, 5,1, 3,0, 4,2, 2,2, 0,2 };
    triangles_[106].indices_ += dummy227;

    //Case 12
    triangles_[225].nrindices_ += 9;
    static char dummy228[] = { 0,2, 0,1, 0,0, -1, 4,2, 4,1, 1,0, 2,0, 3,0 };
    triangles_[225].indices_ += dummy228;

    //Case 12
    triangles_[54].nrindices_ += 9;
    static char dummy229[] = { 2,2, 2,0, 0,1, -1, 0,2, 0,0, 1,1, 4,1, 5,1 };
    triangles_[54].indices_ += dummy229;

    //Case 12
    triangles_[75].nrindices_ += 9;
    static char dummy230[] = { 6,2, 4,1, 2,0, -1, 2,2, 0,1, 3,0, 0,0, 1,0 };
    triangles_[75].indices_ += dummy230;

    //Case 12
    triangles_[156].nrindices_ += 9;
    static char dummy231[] = { 4,2, 0,0, 4,1, -1, 6,2, 2,0, 5,1, 0,1, 1,1 };
    triangles_[156].indices_ += dummy231;

    //Case 12
    triangles_[57].nrindices_ += 9;
    static char dummy232[] = { 3,0, 2,2, 1,1, -1, 1,0, 0,2, 5,1, 0,1, 4,1 };
    triangles_[57].indices_ += dummy232;

    //Case 12
    triangles_[135].nrindices_ += 9;
    static char dummy233[] = { 5,1, 6,2, 3,0, -1, 1,1, 2,2, 1,0, 2,0, 0,0 };
    triangles_[135].indices_ += dummy233;

    //Case 12
    triangles_[108].nrindices_ += 9;
    static char dummy234[] = { 1,0, 4,2, 5,1, -1, 3,0, 6,2, 1,1, 4,1, 0,1 };
    triangles_[108].indices_ += dummy234;

    //Case 12
    triangles_[210].nrindices_ += 9;
    static char dummy235[] = { 1,1, 0,2, 1,0, -1, 5,1, 4,2, 3,0, 0,0, 2,0 };
    triangles_[210].indices_ += dummy235;

    //Case 12
    triangles_[99].nrindices_ += 9;
    static char dummy236[] = { 2,0, 6,2, 4,1, -1, 0,0, 4,2, 0,1, 5,1, 1,1 };
    triangles_[99].indices_ += dummy236;

    //Case 12
    triangles_[30].nrindices_ += 9;
    static char dummy237[] = { 4,1, 4,2, 0,0, -1, 0,1, 0,2, 2,0, 1,0, 3,0 };
    triangles_[30].indices_ += dummy237;

    //Case 12
    triangles_[201].nrindices_ += 9;
    static char dummy238[] = { 0,0, 0,2, 0,1, -1, 2,0, 2,2, 4,1, 1,1, 5,1 };
    triangles_[201].indices_ += dummy238;

    //Case 12
    triangles_[180].nrindices_ += 9;
    static char dummy239[] = { 0,1, 2,2, 2,0, -1, 4,1, 6,2, 0,0, 3,0, 1,0 };
    triangles_[180].indices_ += dummy239;

    //Case 13
    triangles_[105].nrindices_ += 15;
    static char dummy240[] = { 0,0, 0,2, 0,1, -1, 4,1, 2,0, 6,2, -1, 1,1, 3,0, 2,2, -1, 1,0, 4,2, 5,1 };
    triangles_[105].indices_ += dummy240;

    //Case 13
    triangles_[150].nrindices_ += 15;
    static char dummy241[] = { 0,1, 2,2, 2,0, -1, 0,0, 4,1, 4,2, -1, 3,0, 5,1, 6,2, -1, 1,1, 0,2, 1,0 };
    triangles_[150].indices_ += dummy241;

    //Case 14
    triangles_[92].nrindices_ += 9;
    static char dummy242[] = { 3,0, 6,2, 1,1, 0,0, 0,1, -1, 6,2, 4,2, 0,0 };
    triangles_[92].indices_ += dummy242;

    //Case 14
    triangles_[209].nrindices_ += 9;
    static char dummy243[] = { 5,1, 4,2, 3,0, 0,1, 2,0, -1, 4,2, 0,2, 0,1 };
    triangles_[209].indices_ += dummy243;

    //Case 14
    triangles_[53].nrindices_ += 9;
    static char dummy244[] = { 1,0, 0,2, 5,1, 2,0, 4,1, -1, 0,2, 2,2, 2,0 };
    triangles_[53].indices_ += dummy244;

    //Case 14
    triangles_[71].nrindices_ += 9;
    static char dummy245[] = { 1,1, 2,2, 1,0, 4,1, 0,0, -1, 2,2, 6,2, 4,1 };
    triangles_[71].indices_ += dummy245;

    //Case 14
    triangles_[141].nrindices_ += 9;
    static char dummy246[] = { 6,2, 2,0, 5,1, 0,2, 1,1, -1, 2,0, 0,0, 0,2 };
    triangles_[141].indices_ += dummy246;

    //Case 14
    triangles_[228].nrindices_ += 9;
    static char dummy247[] = { 4,2, 4,1, 1,0, 2,2, 3,0, -1, 4,1, 0,1, 2,2 };
    triangles_[228].indices_ += dummy247;

    //Case 14
    triangles_[114].nrindices_ += 9;
    static char dummy248[] = { 0,2, 0,0, 1,1, 6,2, 5,1, -1, 0,0, 2,0, 6,2 };
    triangles_[114].indices_ += dummy248;

    //Case 14
    triangles_[27].nrindices_ += 9;
    static char dummy249[] = { 2,2, 0,1, 3,0, 4,2, 1,0, -1, 0,1, 4,1, 4,2 };
    triangles_[27].indices_ += dummy249;

    //Case 14
    triangles_[202].nrindices_ += 9;
    static char dummy250[] = { 2,0, 2,2, 4,1, 1,0, 5,1, -1, 2,2, 0,2, 1,0 };
    triangles_[202].indices_ += dummy250;

    //Case 14
    triangles_[184].nrindices_ += 9;
    static char dummy251[] = { 4,1, 6,2, 0,0, 1,1, 1,0, -1, 6,2, 2,2, 1,1 };
    triangles_[184].indices_ += dummy251;

    //Case 14
    triangles_[163].nrindices_ += 9;
    static char dummy252[] = { 0,0, 4,2, 0,1, 3,0, 1,1, -1, 4,2, 6,2, 3,0 };
    triangles_[163].indices_ += dummy252;

    //Case 14
    triangles_[46].nrindices_ += 9;
    static char dummy253[] = { 0,1, 0,2, 2,0, 5,1, 3,0, -1, 0,2, 4,2, 5,1 };
    triangles_[46].indices_ += dummy253;
