#!/bin/csh -f

set mods=.mods.dtect
if ( $HDIR == lux || $HDIR == sun5 ) then
    set mods=.mods
endif
set shallow=no
set dodeps=yes
set dodoc=no

source $WORK/Pmake/base/PMinit.csh

parse_args:
if ( "$1" == "--shallow" ) then
    set shallow=yes
else if ( "$1" == "--dtect" ) then
    set mods=.mods.dtect
else if ( "$1" == "--gdi" ) then
    set mods=.mods.gdi
else if ( "$1" == "--nodep" ) then
    set dodeps=no
else if ( "$1" == "--doc" ) then
    set dodoc=yes
else if ( "$1" == "--help" ) then
    echo "Usage: make_all [option]"
    echo " --shallow, Do not remove libs"
    echo " --nodep, Do not create deps"
    echo " --dtect, Only make dTect"
    echo " --gdi, Only make GDI"
    echo " --doc, Create ClassDoc"
    exit 0
else
    goto do_it
endif

shift
goto parse_args

do_it:

if ( $shallow == no ) then
    cdl
    echo "Removing all libs from " `pwd`
    if ( $HDIR == win ) then
	\rm *.lib
	\rm *.dll
	\rm *.dll.a
    else
	\rm *.a
    endif
    ln -s ../*.a .
endif

cdw
dvs update
if ( $dodeps == yes ) then

    set docpdeps=0

    if ( `hostname` == $MAIN_DGB_HOST ) set docpdeps=1
    if ( $HDIR == win ) set docpdeps=1

    if( $docpdeps == 1 ) then
	make dep MODS=$mods
	cd plugins ; make dep
	cd ../spec ; make dep
	cd ..
    else
	cd src ; ./cpdeps
	cd ../plugins ; ./cpdeps
	cd ../spec ; ./cpdeps
	cd ..
    endif
endif
make lib MODS=$mods
make MODS=$mods
cd plugins
make
cd ../spec
make

if ( $dodoc == yes ) then
    cdw
    make doc MODS=$mods
    cd data/dTectDoc/Programmer/Generated
    ./mk_paths_relative
endif

