#ifndef visellipsoid_h
#define visellipsoid_h

/*+
________________________________________________________________________

 CopyRight:	(C) dGB Beheer B.V.
 Author:	Yuancheng Liu
 Date:		10-10-2007
 RCS:		$Id: visellipsoid.h,v 1.1 2007-10-12 21:22:22 cvsyuancheng Exp $
________________________________________________________________________


-*/

#include "visshape.h"
#include "position.h"

class SoMatrixTransform;
class SoSphere;

namespace Geometry { class Pos; };

namespace visBase
{
class Scene;

/*!\brief

Ellipsoid is a basic ellipsoid that is settable in size. It is generated by 
streching a sphere from a scale vector "getWidth()".

*/


class Ellipsoid : public Shape
{
public:
    static Ellipsoid*	create()
			mCreateDataObj(Ellipsoid);

    void		setCenterPos( const Coord3& );
    Coord3		getCenterPos() const;
    
    void		setWidth( const Coord3& );
    Coord3		getWidth() const; 
    
    void		setDisplayTransformation( Transformation* );
    Transformation*	getDisplayTransformation() { return transformation_; }

    int			usePar( const IOPar& );
    void		fillPar( IOPar&, TypeSet<int>& ) const;

protected:
    			~Ellipsoid();
    Transformation*	transformation_;
    SoMatrixTransform*	position_;
    
    static const char*	centerposstr_;
    static const char*	widthstr_;
};

};


#endif
