#ifndef od_helpids_h
#define od_helpids_h
/*+
________________________________________________________________________

 (C) dGB Beheer B.V.; (LICENSE) http://opendtect.org/OpendTect_license.txt
 Author:        K. TIngdahl
 Date:          March 2014
 RCS:           $Id$
________________________________________________________________________

-*/

//General 0
// General_support 1
view_progress 3
uiBatchLaunch 4
uiBatchProgLaunch 5
// General Setup 2
uiSettings 1
uiSetFonts 2
uiLooknFeelSettings 3
uiShortcutsDlg 4
uiPluginMan 5
uiPluginSel 6
uiODSceneMgr::setKeyBindings 7
uiSettings 8
uiLicInstallDlg 9
uiTranslateDlg 10
// General Survey 3
uiSurvey 1
uiSurveyInfoEditor 2
uiSurveyMapDlg 3
uiWorkAreaDlg 4
uiAttrib::DescSetEdimportSet 5
uiCopySurveySIP 6
uiConvertPos 7
uiSurveyInfoEditor 8
uiLatLong2CoordDlg 9
uiGoogleExportSurvey 10
uiSeisWvltMan::getFromOtherSurvey 11
// General Other 4
uiSliceSel 1
uiSliceScroll 2
uimcmddriverimps 3
uiODApplMgr::addTimeDepthScene 4
uiODApplMgrDispatcher:setAutoUpdatePol 5
uiHandleDLSiteFail 6
uiProxyDlg 7
// General Installation 5
uiODInstMgr 1
uiODInstPkgMgr 2
uiODInstMgr::checkInstDir 3
uiODInstMgr::getPackageChoice 4
uiSetupDlg 5
//Object-Management 8
// Object-Management Basic 0
uiSetDataDir 1
Selection 1
uiIOObjSelDlg 1
//Visualisation 50
3D 0
uiSnapshotDlg 1
uiStereoDlg 2
uiGridLinesDlg 3
uiPropertiesDlg 4
uiScenePropertyDlg 5
uiColorBarDialog 6
uiZScaleDlg 7
uiPSViewerSettingDlg 8
uiPrintSceneDlg 9
uiWindowGrabDlg 10
uiWindowGrabDlg 11
uiMultiMapperRangeEditWin 12
uiSurvTopBotImageDlg 13
uiArrowDialog 14
uiMeasureDlg 15
uiVolrenTreeItem 16
uiSeisPartServer::select2DLines 17
uiDirLightDlg 18
uiScenePropertyDlg 19
uiViewer3DPositionsDlg 20
Colors 1
ColorTableDlg 1
uiColorAttrSel 2
uiAutoRangeClipDlg 3
uiColTabImport 4
uiODEditAttribColorDlg 5
Sessions 3
uiODMainAutoSessionDlg 1
//Flat_displays 51
Display 0
uiFlatViewStdControl 0
uiFlatViewPropDlg 1
uiEMObjectTabsWin 2
2DPSViewer 1
uiViewer2DMainWin 0
uiViewer2DPosDlg 1
uiViewer2DSelDataDlg 2
uiViewer2DMainWin::displayAngle 3
//Attributes 101
Definition 0
uiCoherencyAttrib 0
uiConvolveAttrib 1
uiDipFilterAttrib 2
uiEnergyAttrib 3
uiEventAttrib 4
uiFingerPrintAttrib 5
uiFrequencyAttrib 6
uiFreqFilterAttrib 7
uiInstantaneousAttrib 8
uiMathAttrib 9
uiPositionAttrib 10
uiReferenceAttrib 11
uiScalingAttrib 12
uiShiftAttrib 13
uiSimilarityAttrib 14
uiSpecDecompAttrib 15
uiVolumeStatisticsAttrib 16
uiPreStackAttrib 17
uiHorizonAttrib 100
uiGapDecon 101
uiMatchDelta 102
uiDeltaResample 103
uiTextureAttrib 104
uiSampleValueAttrib 105
Selection 1
uiAttribDescSetEd 0
uiAttrSelDlg(No_NN) 1
uiAttrInpDlg 2
uiGetFileForAttrSet 3
uiAttrSrchProcFiles 4
uiAutoAttrSelDlg 5
uiAttribDescSetEd::defaultSet 6
uiTrcPositionDlg 7
Output 2
uiAttrVolOut 0
uiRestartBatchDialog 1
uiClusterJobProv 2
uiMultOutSel 3
Utilities 3
uiAttrSetMan 0
uiEvaluateDlg 1
uiFPAdvancedDlg 2
uiFreqTaperDlg 3
//Seismics 103
I/O 0
uiSeisImpCBVS(I) 1
uiSEGYExpMore 2
uiSEGYExpTxtHeaderDlg 3
uiSEGYImpSimilarDlg 4
uiSEGYExamine 5
uiSEGYDefDlg 6
uiSEGYExp 7
uiSEGYReadRev1Question 8
uiSEGYReadDlg 9
uiSEGYReadPreScanner 10
uiSeisIOSimple(I) 11
uiSeisIOSimple(E) 12
uiSeisPreLoadMgr 13
uiSeisPreLoadMgrSel2D 14
uiSEGYExp::doWork 15
uiDZTImporter 16
uiSeisFmtScaleDlg 17
uiSEGYFileManip 19
uiSEGYBinHdrEdDlg 20
uiSEGYFileManipHdrCalcEd 21
uiSeisImpCBVSFromOtherSurveyDlg 22
Manage 1
uiSeisFileMan::3D 0
uiSeisImpCBVS(C) 1
uiMergeSeis 2
uiSeis2DMan 3
uiSeisDump2DGeom 4
uiSeisBrowser 5
uiPosProvSel 6
uiSeisMultiCubePS 7
uiSeisCopyLineSet 8
uiSeis2DFileManMergeDlg 9
uiSeis2DExtractFrom3D 10
uiSeisFileMan::2D 11
uiGoogleExport2DSeis 12
uiSeis2DMultiLineSelDlg 13
ui2DGeomManageDlg 14
uiManageLineGeomDlg 15
uiGeom2DImpDlg 16
uiDataPointSetMan 17
uiDataPointSetMerger 18
uiBodyOperatorDlg 19
uiBodyRegionDlg 20
uiImplicitBodyValueSwitchDlg 21
uiImplBodyCalDlg 22
Processing 2
uiSeisMMProc 0
PreStack::uiAGC 1
PreStack::uiMute 2
PreStack::uiVerticalStack 3
VolProc::uiChain 4
PreStack::uiImportMute 5
PreStack::uiExportMute 6
PreStack::uiImportMute(Pars) 7
uiImportVelFunc 8
uiImportVelFunc(Pars) 9
PreStack:uiBatchProcSetup 10
Vol::ProcuiBatchSetup 11
uiBatchTime2DepthSetup 12
PreStack::uiProcSel 13:
Vel:uiBatchVolumeConversion 14:
uiSeisBayesPDFInp 15
uiSeisBayesNorm 16
uiSeisBayesSeisInp 17
uiSeisBayesOut 18
uiAngleMuteComputer 19
uiAngleMute 20
uiResortSEGYDlg 21
uiMultiWellCreateLogCubeDlg 22
uiCreate2DGrid 23
uiSeis2DTo3D 24
uiCreateLogCubeDlg 25
uiAngleCompAdvParsDlg 26
uiProcSettings 27
Wavelets 3
uiSeisWvltMan 0
uiSeisWvltImp 1
uiSeisWvltManCrWvlt 2
uiSeisWvltImp(Pars) 3
uiWaveletExtraction 4
uiSeisWvltSliderDlg 5
uiSeisWvltTaperDlg 6
uiSeisWvltMerge 7
uiWaveletDispPropDlg 8
Prestack 4
uiSeisPrestackMan::3D 0:
uiSeisPrestackMan::2D 1:
uiPreStackCopyDlg 2
uiPreStackMergeDlg 3
uiRayTrcParamsDlg 4
LINKS 5
uiMadagascarMain 0
uiMadIOSelDlg 1
uiGMTMainWin 2
Analysis 6
uiChain 0
uiStepDialog 1
uiStepDialog 2
uiStepDialog 3
uiStepDialog 4
uiStepDialog 5
uiAddFunction 6
uiVelocityDescDlg 7
uiStepDialog 8
uiEditFunction 9
uiVoxelConnectivityFilter 10
//Surfaces 104
Horizons 0
uiImportHorizon 0
uiExportHorizon 1
uiImportHorAttrib 2
uiChangeSurfaceDlg 3
uiEMHorizonEditorSetting 4
uiHor3DFrom2DDlg 5
uiArr2DFilterParsDlg 7
uiTableImpDataSel(3DSurfaces) 8
uiTableImpDataSel(2DSurfaces) 9
uiflattenedcube 10
uisnapptoevent 11
uiHor2DFrom3DDlg 12
uiInverseDistanceArray2DInterpol 13
uiImportHorizon2D 14
uiHorizonShiftDialog 15
uiBulkHorizonImport 16
Faults 1
uiImportFault 0
uiExportFault 1
uiTableImpDataSel(Faults) 2
uiImportFaultStick 3
uiImportFaultStick 4
uiExportFaultStick 5
uiTableImpDataSel(FaultStickSet3D) 6
uiTableImpDataSel(FaultStickSet2D) 7
uiFaultStickTransferDlg 8
Manage 2
uiSurfaceMan 0
uiSurface2DMan 1
uiHorizonRelationsDlg 2
HorizonModifyDlg 3
uiFaultStickSetsManage 4
uiFaultsManage 5
uiCopySurface::3D 6:
uiCopySurface::2D 7:
uiCopySurface:StickSets 8:
uiCopySurface:Faults 9:
uiHorizonMergeDlg 10
Display 3
uiMultiSurfaceReadDlg 0
uiWriteSurfaceDlg 1
uiContourParsDlg 2
Attributes 4
uiAttrSurfaceOut 0
uiAttrTrcSelOut 1
uiAttrTrcSelOut 2
uiAttrStrAmplOut 3
uiIsopachMaker 4
uiCalcPoly2HorVol 5
uiStoreAuxData 6
uiHorAttr2Geom 7
uiHorGeom2Attr 8
//Picking 105
I/O 0
uiFetchPicks 0
uiImpExpPickSet 1
uiImpExpPickSet 2
uiStorePicks 3
uiMergePickSets 4
uiTableImpDataSel(picks) 5
uiPickSetMan 6
Other 1
uiGoogleExportPolygon 0
uiSetPickDirs 1
//Wells 107
I/O 0
uiWellImportAsc 0
uiWellImpSegyVsp 1
uiWellImportAsc 2
uiD2TModelGroup 3
uiWellImpPptDlg 4
uiNewWellDlg 5
uiStoreWellDlg 6
uiSimpleMultiWellCreate 7
uiSimpleMultiWellCreateReadData 8
uiTableImpDataSel(wells) 9
uiBulkTrackImport 10
uiBulkLogImport 11
uiBulkMarkerImport 12
Manage 1
uiWellMan 0
uiMarkerDlg 1
uiLoadLogsDlg 2
uiExportLogs 3
uiReadMarkerFile 4
uiD2TModelDlg 5
uiD2TModelReadDlg 6
uiWellTrackDlg 7
uiWellTrackReadDlg 8
uiTableImpDataSel(markers) 9
uiWellLogCalc 10
uiGoogleExportWells 11
uiWellLogCalcRockPhys 12
Display 2
uiWellDispPropDlg 0
Attributes 3
uiCreateAttribLogDlg 0
uiWellLogToolWinMgr 1
Well_Ties 4
WellTie::uiMgrDlg 0:
WellTie::uiTieWin 1:
WellTie::uiInfoDlg 2:
WellTie::uiSaveDataDlg 3:
uiCheckShotEdit 4
//Tracking 108
I/O 0
Tracking::Wizard 0:
Tracking::uiSetupGroup 1:
Display 1
uiSurfaceRelationDlg 0
//Random_lines 109
General 0
uiWell2RandomLineDlg 0
uiGenRanLinesByContour 1
uiGenRanLinesByShift 2
uiGenRanLinesFromPolygon 3
uiODRandomLineTreeItem 4
uiSeisRandTo2DLineDlg 5
uiRandomLinePolyLineDlg 6
uiGoogleExportRandomLine 7
//Stratigraphy 110
General 0
uiStratTreeWin 0
uiStratUnitDlg 1
uiStratLevelDlg 2
uiStratLinkLvlUnitDlg 3
uiStratLithoDlg 4
uiStratContentsDlg 5
uiEditPropRefMathDef 6
uiEditPropRefMathDef:RockPhysReq 7:
uiStratSynthExport 8
uiStartSynthOutSel 9
uiStratSynthLayerModFRPPropSelector 10
uiStratEditLayer 11
uiStratSimpleLayerModDisp 12
Properties 1
uiManPROPS 0
uiEditPropRef 1
uiSelectPropRefs 2
uiElasticPropSelDlg 3
BasicModelling 2
uiSingleLayerGeneratorEd 0
uiSynthToRealScale 1
uiStratLayerModel:checkUnscaledWavelet 2:
Crossplotting 3
uiStratSynthCrossplot 0
uiSingleAttribEd 1
uiLaySeqAttribEd 2
//Crossplots 111
General 0
uiDataPointSet 0
uidataPointSetSave 1
uiDataPointSetCrossPlotterPropDlg 2
uiCreateDPSPDF 3
uiSelectionSettDlg 4
uiDPSOverlayPropDlg 5
uiSelColorDlg 6
uiImpPVDS 7
uiTableImpDataSel(pvds) 8
uiExpSelectionArea 9
uiReadSelGrp 10
uiDPSSelectednessDlg 11
uiVariogramDlg 12
uiVariogramDisplay 13
Extraction 1
uiAttribCrossPlot 0
uiWellAttribCrossPlot 1
uiPosFilterSetSel 2
//Probability_density_functions 112
// Probability_density_functions_I/O 0
uiImpRokDocPDF 0
uiExpRokDocPDF 1
// Probability_density_functions Manage 1
uiProbDenFuncMan 0
uiEditProbDenFunc 1
uiProbGenFuncGen 2

#endif

