<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'TextLinter' => 'linter/TextLinter.php',
    'dGBLintEngine' => 'engine/dGBLintEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'TextLinter' => 'ArcanistLinter',
    'dGBLintEngine' => 'ArcanistLintEngine',
  ),
));

