#_______________________Pmake___________________________________________________
#
#	Makefile : 	General utilities
# 	Mar 2004	Nanne Hemstra
#	RCS :		$Id: Makefile,v 1.2 2004-05-11 12:36:21 kristofer Exp $
#_______________________________________________________________________________


SRC.cc	:= SoCameraInfo.cc SoCameraInfoElement.cc SoDepthTabPlaneDragger.cc \
	   SoForegroundTranslation.cc SoIndexedTriangleFanSet.cc \
	   SoManLevelOfDetail.cc SoPerspectiveSel.cc \
	   SoPlaneWellLog.cc SoShapeScale.cc SoTranslateRectangleDragger.cc \
	   SoRandomTrackLineDragger.cc SoGridSurfaceDragger.cc \
	   SoMeshSurfaceBrick.cc SoMeshSurfaceBrickWire.cc \
	   SoMeshSurfaceSquare.cc SoMeshSurface.cc SoArrow.cc \

USECOIN := yes

include make.od.Defaults
include make.Targets
