/*+
 * COPYRIGHT: (C) de Groot-Bril Earth Sciences B.V.
 * AUTHOR   : A.H. Bril
 * DATE     : Nov 2002
 * FUNCTION : Generate file to include in make.Vars
-*/

static const char* rcsID = "$Id: GenModDeps.cc,v 1.9 2004-01-21 13:46:25 bert Exp $";

#include "prog.h"
#include "strmprov.h"
#include "bufstringset.h"
#include "filegen.h"
#include "timefun.h"
#include <stdlib.h>
#include <iostream>

class Dep
{
public:
    			Dep( const char* m )
			    : name(m)	{}
    bool		operator ==( const char* s ) const
			    { return name == s; }

    BufferString	name;
    BufferStringSet	mods;
};


int main( int argc, char** argv )
{
    int arg1 = 1; bool html = false;
    if ( argc >= 3 && !strcmp(argv[1],"--html") )
	{ html = true; arg1 = 2; }
    if ( argc-arg1+1 < 3 )
    {
	cerr << "Usage: " << argv[0]
	     << " [--html] input_ModDeps_file output_file" << endl;
	exitProgram( 1 );
    }
    StreamProvider spin( argv[arg1] );
    StreamData sdin = spin.makeIStream();
    if ( !sdin.usable() )
    {
	cerr << argv[0] << ": Cannot open input stream" << endl;
	exitProgram( 1 );
    }
    else if ( sdin.istrm == &cin )
	cout << "Using standard input." << endl;
    istream& instrm = *sdin.istrm;

    if ( !instrm )
    {
	cerr << "Bad ModDeps file" << endl;
	exitProgram( 1 );
    }
    StreamProvider spout( argv[arg1+1] );
    StreamData sdout = spout.makeOStream();
    if ( !sdout.usable() )
    {
	cerr << argv[0] << ": Cannot open output stream" << endl;
	exitProgram( 1 );
    }
    ostream& outstrm = *sdout.ostrm;

    char linebuf[1024];
    char wordbuf[256];
    ObjectSet<Dep> deps;
    while ( instrm )
    {
	instrm.getline( linebuf, 1024 );
	char* bufptr = linebuf; 
	skipLeadingBlanks(bufptr);
	removeTrailingBlanks(bufptr);
	if ( ! *bufptr || *bufptr == '#' )
	    continue;

	char* nextptr = (char*)getNextWord(bufptr,wordbuf);
	if ( ! wordbuf[0] ) continue;
	int l = strlen( wordbuf );
	if ( wordbuf[l-1] == ':' ) wordbuf[l-1] = '\0';
	if ( ! wordbuf[0] ) continue;

	*nextptr++ = '\0';
	skipLeadingBlanks(nextptr);

	Dep* newdep = new Dep( wordbuf ) ;
	BufferStringSet filedeps;
	while ( nextptr && *nextptr )
	{
	    skipLeadingBlanks(nextptr);
	    nextptr = (char*)getNextWord(nextptr,wordbuf);
	    if ( !wordbuf[0] ) break;

	    if ( wordbuf[1] != '.' || (wordbuf[0] != 'S' && wordbuf[0] != 'D') )
		{ cerr << "Cannot handle dep=" << wordbuf << endl;
		    exitProgram(1); }

	    filedeps.add( wordbuf );
	}


	BufferStringSet depmods( false );
	for ( int idx=filedeps.size()-1; idx>=0; idx-- )
	{
	    const char* filedep = filedeps.get(idx).buf();
	    const char* modnm = filedep + 2;
	    if ( *filedep == 'S' )
	    {
		depmods.add( modnm );
	        continue;
	    }

	    Dep* depdep = find( deps, modnm );
	    if ( !depdep )
		{ cerr << "Cannot find dep=" << modnm << endl; exitProgram(1); }

	    for ( int idep=depdep->mods.size()-1; idep>=0; idep-- )
	    {
		const char* depdepmod = depdep->mods.get(idep).buf();
		if ( depmods.indexOf(depdepmod) < 0 )
		    depmods.add( depdepmod );
	    }
	}
	if ( depmods.size() < 1 )
	    { delete newdep; continue; }
	deps += newdep;

	for ( int idx=depmods.size()-1; idx>=0; idx-- )
	    newdep->mods += depmods[idx];
    }
    sdin.close();

    if ( html )
    {
	outstrm << "<html>\n<!-- Generated by " << File_getFileName(argv[0])
	        << " (" << Time_getLocalString()
	        << ") -->\n\n\n<body bgcolor=\"#dddddd\">"
		    "<title>OpendTect source documentation</title>\n\n"
		    "<center><h3>Open"
		<< GetProjectVersionName()
		<< " modules</h3></center>\n\n"
		   "<TABLE align=\"center\" summary=\"Modules\""
			   "WIDTH=\"75%\" BORDER=\"1\">"
		<< endl;

	BufferStringSet allmods;
	for ( int idx=0; idx<deps.size(); idx++ )
	    allmods.add( deps[idx]->name );
	allmods.sort();

	for ( int idep=0; idep<allmods.size(); idep++ )
	{
	    const BufferString& nm = allmods.get(idep);
	    outstrm << "<TR align=center>\n";

	    outstrm << " <TD><b>" << nm << "</b></TD>\n <TD><a href=\""
	    << nm << "/index.html\">Main Page</a></TD>\n <TD><a href=\""
	    << nm << "/classes.html\">Class Index</a></TD>\n <TD><a href=\""
	    << nm << "/hierarchy.html\">Class Hierarchy</a></TD>\n <TD><a href=\""
	    << nm << "/annotated.html\">Compound List</a></TD>\n</TR>\n\n";
	}

	outstrm << "\n</TABLE>\n\n<body>\n<html>" << endl;
    }

    else
    {
	for ( int idx=0; idx<deps.size(); idx++ )
	{
	    Dep& dep = *deps[idx];

	    outstrm << 'L' << dep.name << " :=";
	    for ( int idep=0; idep<dep.mods.size(); idep++ )
		outstrm << " -l" << (const char*)(*dep.mods[idep]);
	    outstrm << endl;
	    outstrm << 'I' << dep.name << " :=";
	    for ( int idep=0; idep<dep.mods.size(); idep++ )
		outstrm << ' ' << (const char*)(*dep.mods[idep]);
	    outstrm << endl;

	}
    }


    sdout.close();
    exitProgram( 0 ); return 0;
}
