#!/bin/csh -f
#________________________________________________________________________
#
# Copyright:    (C) 1995-2022 dGB Beheer B.V.
# License:      https://dgbes.com/licensing
#________________________________________________________________________
#
# Changing the dependency path of the libraries on MAC platform.
#

if ( $#argv < 1 ) then
   echo "Usage : $0 Library name to change the dependency"
   exit 1
endif

set bnry=$1
echo "Changing the dependency path in : $bnry"
if ( -f ${bnry} ) then
	set deplist=`otool -L ${bnry} | sed 's/ .*//'`
	foreach dep ( ${deplist} )
		set libnm=`basename ${dep}`
		set rootdir=`echo ${dep} | cut -c 2-4`
		set insttest="${dep}"
		set depmodified=`echo "${dep}" | sed 's/\//_/g'`
		set test=`echo "${depmodified}" | awk '{n=split($0,a,"_"); print a[n]}'`
		set chgdep=false

		if ( ${test} == "libfontconfig.1.dylib" || ${test} == "libfreetype.6.dylib" || ${test} == "libcrypto.1.1.dylib" || ${test} == "libshp.1.dylib" || ${test} == "libproj.14.dylib" || ${test} == "libpng16.16.dylib" || ${test} == "libssl.1.1.dylib" ) then
		    set chgdep=true
		endif

		if ( $rootdir != "Sys" && ${chgdep} == "true" ) then
		    if( ${test} == "libssl.1.1.dylib" || ${test} == "libcrypto.1.1.dylib" ) then 
		        install_name_tool -change ${dep} @executable_path/../Resources/OpenSSL/${libnm} ${bnry}
		    else
		        install_name_tool -change ${dep} @executable_path/../Frameworks/${libnm} ${bnry}
		    endif
		endif
	end
endif
